[project]
name = "luxethreads"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=47.0.0",
    "flask==3.0.3",
    "flask-migrate>=4.1.0",
    "flask-sqlalchemy==3.1.1",
    "pymysql>=1.1.2",
    "python-dotenv>=1.2.2",
]
