"""add whatsapp/instagram to customer and payment fields to order

Revision ID: 56fda80f54ef
Revises: ea52c189de57
Create Date: 2026-08-09 05:43:43.521290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fda80f54ef'
down_revision = 'ea52c189de57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('instagram_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('channel')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('instagram_id')
        batch_op.drop_column('whatsapp_number')

    # ### end Alembic commands ###
