"""add vendor_id and vendor_payout to order_items

Revision ID: ea52c189de57
Revises: 4e63042e009e
Create Date: 2026-08-09 05:37:37.900734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea52c189de57'
down_revision = '4e63042e009e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categories_slug'), ['slug'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_customers_email'), ['email'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vendor_payout', sa.Float(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_order_items_vendor_id_vendors'), 'vendors', ['vendor_id'], ['id'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_vendors_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vendors_email'), type_='unique')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_items_vendor_id_vendors'), type_='foreignkey')
        batch_op.drop_column('vendor_payout')
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_customers_email'), type_='unique')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_slug'), type_='unique')

    # ### end Alembic commands ###
